name: Metrics
on:
  # Roda a cada 24 horas
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente
  workflow_dispatch:
  # Roda quando você faz push na branch master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token (o GitHub já cria isso sozinho, não precisa mexer)
          token: ${{ secrets.GITHUB_TOKEN }}

          # Opções Básicas
          user: joaorizzo0112
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Linguagens
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          
          # Sequência de código (Substituto estável do Streak)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          
          # Linhas de código adicionadas
          plugin_lines: yes
